"""Added columns to employee

Revision ID: d6d967edf497
Revises: 4ecf7290a8c0
Create Date: 2024-04-22 10:12:31.002053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d967edf497'
down_revision = '4ecf7290a8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('department')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
